// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mnitzgoythqqevhtkitj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1uaXR6Z295dGhxcWV2aHRraXRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxOTA5MzUsImV4cCI6MjA2NTc2NjkzNX0.Jr38d0BgEIztZfIz2ZZ4fj-r0eKhfBEjwob5WWDXG2U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);